modLoader = "javafml"
loaderVersion = "[40,)"
license = "AGPL v3"
[[mods]]
modId = "itemfx"
version = "${file.jarVersion}"
displayName = "ItemSpecialEffects"
credits = "Elona and her author Noa, for providing ideas and resources"
authors = "Tapio"
description = '''
'''